services:
  - type: web
    name: gemini-summarizer-api
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
